name: Deploy quiz_edication_bot

on:
  push:
    branches:
      - main

permissions:
  contents: read         # Разрешения на доступ к коду репозитория
  packages: write        # Разрешения на загрузку пакетов
  id-token: write        # Разрешения для работы с токенами
  actions: read          # Разрешения для работы с действиями

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: установка uv
        uses: astral-sh/setup-uv@v5

      - name: Установка зависимостей
        run: uv sync --all-extras --dev


  build_and_push_in_GHCR:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Вход в GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка Docker образа
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/quiz_edication_bot:latest .

      - name: Push Docker образ в GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/quiz_edication_bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_in_GHCR

    steps:
      - name: клонирование репозитория в среду выполнения
        uses: actions/checkout@v4

      - name: Вход на сервер по SSH и деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Входим в GHCR
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            
            # Останавливаем и удаляем старый контейнер, если он есть
            docker rm -f quiz_edication_bot || true
            
            # Полная очистка кэша, образов и ненужных данных
            docker system prune -af --volumes
            
            # Запускаем контейнер
            docker run --pull=always -d \
              --name quiz_edication_bot \
              -v /root/quiz_edication_bot/paswords.py:/app/paswords.py \
              -v /root/quiz_edication_bot/loggs.log:/app/loggs.log \
              ghcr.io/${{ github.repository_owner }}/quiz_edication_bot:latest
